export const API_CONTEXT = 'http://192.168.0.13:3000';
export const TEMP_TOKEN = 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2MiIsImlhdCI6MTU2MDY1OTk3MywiZXhwIjoxNTYxMjY0NzczLCJuYW1lIjoiR3VzdGF2byBGZWxpcGUgU8OpcmdpbyBkYSBDb25jZWnDp8OjbyIsImVtYWlsIjoiY2F1ZS5jZXNhckBtZW5kZXN3ZWIuY29tLmJyIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfQ09MTEVDVE9SIn1dfQ.fNUVCYNow5P-wnleSGhX4opR8EWzqd2G7vGlJirsV4kS9vtgoUkktZk79uPZHpmKM7TNcARZtRAr888F4a6GgA'

export const API = {
	GET_MY_PENDENCIES: API_CONTEXT + '/getMyPendencies',
	GET_PENDENCY: API_CONTEXT + '/getMyPendencyById/{id}',
	GET_RISKS: API_CONTEXT + '/getRisks',
	GET_OBSERVATION: API_CONTEXT + '/getObservations',
};
